[package]
name = "chip8-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
pixels = "0.15.0"
rand = "0.9.2"
rodio = { version = "0.21.1", default-features = false, features = ["playback"]}
winit = "0.30.12"
